### ISSUE TITLE
CalDAV Integration Testing

### ISSUE THREAD

**Issue by alainm23** [alainm23/planify#1118]
In this space you can report or comment any bug or improvement for this integration.

You can install a development version from [here](https://github.com/alainm23/planify/actions/runs/7678355432/artifacts/1199584547)

This is a test instance and will not cross over with your main instance of Planify installed on your computer.
For now Planify only supports Nextcloud account. The features supported so far are.

- [x] Login with a Nextcloud account.
- [ ] Edit the account.
- [x] Delete the account.
- [x] Synchronise from servers.
- [x] Create, edit and delete task lists.
- [x] Create, edit and delete a task.
- [x] Completing a task.
- [x] Due date
- [x] Priorities
- [x] Tags
- [x] Pinned
- [x] Recurrent tasks
- [x] Sub tasks
- [x] Move tasks to another list.
- [x] Only display VTODO task list.
- [ ] Offline support
- [x] Use libsecret to store the user's password.

**Comment by madpipeline** [comment]
I have installed the flatpak beta version using this command:

```
flatpak install --user https://dl.flathub.org/build-repo/77878/io.github.alainm23.planify.flatpakref
```

This provided a beta instance of the application, and I could choose which instance to start: beta or release.

## What works:
* Connecting to a nextcloud instance using an app passowrd
* Creating new task list
* Downloading changes (new tasks added forn MextCloud interface) (including task notes)

## What does not work
* Adding a new task anywhere in the app crashes the app
* Checking a task (mark as done) does not get uploaded

## Cosmetic notes
* CalDav fields are prepopulated, they should be hints and disappear when starting typing
* No means to edit a CalDav connection after adding it

**Comment by alainm23** [comment]
@madpipeline Thank you for your comments. Which Nextcloud server are you using? I understand that you cannot create any tasks?

**Comment by madpipeline** [comment]
Nextcloud Hub 7 (28.0.1)

Tasks app version: 0.15.0

**Comment by alainm23** [comment]
@madpipeline  For the option to edit the account, you only need to enable the username and password fields. If the user wants to change the server URL, it would be better to delete the account and log in again.

**Comment by alainm23** [comment]
I would like to comment that for now, the password is saved as a property within the Planify configuration, I understand that the best way would be to use Libsecret, if someone has a quick example for this I would be grateful.

**Comment by antrmn** [comment]
**Bug**

Planner should only show VTODO capable calendars.

When syncing to my Nextcloud instance, I get this:

![Screenshot from 2024-01-24 18-20-34](https://github.com/alainm23/planify/assets/37816362/267f2514-8857-4a29-a484-04f05257a3f7)

`Personale` is my only calendar that is meant to handle tasks, as can be seen on DAVx5:

![Screenshot_20240124-182046~2](https://github.com/alainm23/planify/assets/37816362/240c5a01-a103-48d8-a1d9-07811e44f96b)

+ `Appelli` is just a calendar
+ `Date di nascita dei contatti` is a read-only automatically generated calendar that shows all birthdays of my contacts
+ `Lezioni` is just a calendar
+ `Personal` is both a calendar and a tasks list. This is the only one that should appear in Planify

**Feature request**

Pinned tasks could be translated to a (default or manually specified) tag in the CalDAV source.

**Question**

Have you already considered using Evolution Data Server as a backend for handling tasks? If yes, what blocked you from doing so?

**Comment by alainm23** [comment]
@antrmn Thank you for reporting it, I have just reproduced the error, it is being reviewed. 

The reason why EDS is not used [here](https://github.com/alainm23/planify/issues/1049#issuecomment-1849960447).

**Comment by alainm23** [comment]
@antrmn I have to make one more filter to read only VTODO and not VEVENT calendars.

![image](https://github.com/alainm23/planify/assets/33765137/7b5fd833-ffba-4bfb-a3c2-c62470b70218)

**Comment by oktayacikalin** [comment]
I've installed the latest dev version and connected to my Nextcloud (28.0.1) account. It could sync and show all tasks, including sub-tasks. Overall, it looks great so far.

What I'm missing is manual syncing of calendars (i.e. working in tandem with my Android phone or the web UI), and creating new tasks. I tried to use the quick add method, but every time I try to add a task, it would not let me choose a project/calendar.

Ah - and the desktop file is trying to run the stable version.

**Comment by alainm23** [comment]
@oktayacikalin You are right, CalDAV type projects still need to be added in Quick Add.

**Comment by alainm23** [comment]
@antrmn Pinned tasks are displayed with a pin in the Nextcloud web client.
Currently pinned tasks are only shown in Pinboard view, but I plan to make it Github-style when you pin an issue. 

![image](https://github.com/alainm23/planify/assets/33765137/251e102e-f2c8-46d3-8902-34a197417fbd)

**Comment by alainm23** [comment]
Hi guys, I have a new version for testing, the following has been fixed and added:

[io.github.alainm23.planify.Devel.json](https://github.com/alainm23/planify/files/14051028/io.github.alainm23.planify.Devel.json)

- [x] Only show list of tasks of type VTODO.
- [x] Now you can move tasks between task lists.
- [x] Improved support for subtasks.
- [x] Added task list selection in Quick Add.

**Comment by oktayacikalin** [comment]
- After removing and re-adding the sync, only the VTODO calendars got fetched. :+1: 
- Quick Add to a list works now as expected. :+1: 
- Moving subtasks between tasks works. :+1: 
- Moving tasks via context menu to another list works. :+1: 
- Found the manual sync button :+1: 

What I'm missing:
- Drag a task from one list to another.
- Convert subtask to task.
- Manually sync only a specific list.
- I've a task "Treppenhausreinigung" with a bunch of subtasks which are scheduled for repetition. All those subtasks appear in the list and not below the task itself.

I've also problems with emojis. Where should I report them? Create a different issue, I guess?

**Comment by alainm23** [comment]
Hello and thanks for your comments.
> Drag a task from one list to another.

I will consider this as a new feature.

>Convert subtask to task.

It should work by dragging the child task off the parent, but it still needs a couple of tweaks to get it to work.

>Manually sync only a specific list.

I don't think it's that complicated, Planify does a list-by-list query.

>I've a task "Treppenhausreinigung" with a bunch of subtasks which are scheduled for repetition. All those subtasks appear in the list and not below the task itself.

I will look into this further, I am not sure how CalDAV works with recurring tasks.

**Comment by alainm23** [comment]
@oktayacikalin  What is your problem with emojis, can't you see them?

**Comment by oktayacikalin** [comment]
> I will look into this further, I am not sure how CalDAV works with recurring tasks.

I've taken a bunch of screenshots on my Android phone. Here are some examples of what the app writes into the reoccurring events for later re-scheduling:

- every Thursday: FREQ=WEEKLY,BYDAY=TH
- every week after last completion: FREQ=WEEKLY;REL
- every month at the 25th: FREQ=MONTHLY;BYMONTHDAY=25
- every month after last completion: FREQ:MONTHLY;REL
- every day: FREQ=DAILY
- every 25th of January: FREQ=YEARLY;MYMONTH=1;BYMONTHDAY=25
- every year after last completion: FREQ=YEARLY;REL
- every 2 months on the 25th: FREQ=MONTHLY;INTERVAL=2;MYMONTHDAY=25

All apps I've tested, which support reoccurring events, do write those rules into the event and when you complete it, the app just re-schedules it according the rules. So you won't see copies in the past. Also in order not to quickly blow up the calendar database table.
Nextcloud Tasks does not care about reoccurring event data and just handles them as simple tasks.

But I think, in this case, Planify does not interpret the relations correctly, thus displaying the subtasks as tasks. I'll try to extract these so that we can learn more.

**Comment by oktayacikalin** [comment]
> What is your problem with emojis, can't you see them?

- In general, I can see the emojis in lists and tasks. It looks like more complex emojis are not handled correctly.
- Within the Today → Overdue list, my list called "🥷 Persönlich 📝" does show as seen in the screenshot.
- I'm getting a lot of errors in the console about invalid UTF-8 strings. See the log attached.

![Bildschirmfoto vom 2024-01-26 02-11-54](https://github.com/alainm23/planify/assets/687189/e5d086da-4d97-47a0-aef7-7634d9db3895)

[planify.log](https://github.com/alainm23/planify/files/14059211/planify.log)

**Comment by umgpy** [comment]
Thank you for the great work @alainm23! Tasks with sub tasks created on Planify become regular tasks after syncing with the nextcloud instance. But once it is fixed on nextcloud it maintains the task:sub-task relation.

**Comment by alainm23** [comment]
@umgpy That's right, and I've already fixed it in my development environment, now I'm working on Tags support, I'll send a test version when I finish it. Offline support and recurring tasks are still pending.

**Comment by alainm23** [comment]
@oktayacikalin Thank you very much, I see that the problem with the emoji is not only from Nextcloud, it is a bug of Planify when shortening the project name, I will register it as a bug.

**Comment by alainm23** [comment]
How do you create recurring tasks? Are you using tasks.org?

**Comment by umgpy** [comment]
Yes using tasks.org for the recurrent tasks, although I cannot seem to create it from Nextcloud. It does show up successful on the calendar.

**Comment by alainm23** [comment]
Hi guys I have another new development version of Planify with the following changes:

https://github.com/alainm23/planify/actions/runs/7678355432/artifacts/1199584547

- Added support for Tags.
- Now it is possible to create subtasks using Quick Add or drag and drop.
- Manually sync only a specific list.
- Convert a subtask into a normal task by drag and drop.

**Comment by alainm23** [comment]
![image](https://github.com/alainm23/planify/assets/33765137/fff6f16c-e098-49e6-834c-258af32dc59f)

**Comment by alainm23** [comment]
I would like to know your opinion, the CalDAV account does not have permission to edit the Deck type task lists, only viewing, should Planify?

**Comment by oktayacikalin** [comment]
BUG: When I add a tag to a task in Nextcloud, then open the task in Planify and want to edit the tags, the tags from Nextcloud are not selected. And when I close the tag popup, those even get removed.

**Comment by oktayacikalin** [comment]
BUG: When I create a tree of nested tasks with a depth of 3, then delete the whole tree in Planify, only the root task is removed from NC. Then I can see the rest of the branch in NC. Refreshing in Planify does not show it.

I think, all subtasks should be removed too.

**Comment by oktayacikalin** [comment]
> I would like to know your opinion, the CalDAV account does not have permission to edit the Deck type task lists, only viewing, should Planify?

I think, Deck type tasks should only appear in a board view. Otherwise, it's confusing.

**Comment by oktayacikalin** [comment]
BUG: When I drag the Add-Button on a blue insert-bar within a tree, the task is being created at the root level of the list, and not within the tree.

**Comment by BeatLink** [comment]
BUG: Planify wont load nextcloud calendars that also contain todo lists. It will only load lists without the calendar

**Comment by alainm23** [comment]
@oktayacikalin Thanks, I'm already fixing the bugs you mention. For the board views from Nextcloud, maybe we could add it as an improvement later, for the moment they are shown as read-only.

**Comment by alainm23** [comment]
@BeatLink Hello old friend, what is your life? haha, thanks for writing, I really do not understand very well the error you comment, could you explain it better, I'm a noob in CalDAV, but I learn fast.

**Comment by antrmn** [comment]
> @BeatLink Hello old friend, what is your life? haha, thanks for writing, I really do not understand very well the error you comment, could you explain it better, I'm a noob in CalDAV, but I learn fast.

I think it is related to my issue explained [above](https://github.com/alainm23/planify/issues/1118#issuecomment-1908623696). In my previous comment, `Personale` is both a calendar and a task list and in fact I can confirm that it does not apper in Planify.

Regarding your reply above:

> I have to make one more filter to read only VTODO and not VEVENT calendars.

I don't know exactly how the `cal:supported-calendar-component-set` is filled when a collection can store both VTODOs and VEVENTs, but maybe this property can hold multiple values?

**Comment by alainm23** [comment]
@antrmn That's right, the calendar can support both types, thank you I will validate it better.
![image](https://github.com/alainm23/planify/assets/33765137/aca0d617-2f5e-41a9-9e0a-cf83160f94c3)

**Comment by oktayacikalin** [comment]
> @oktayacikalin Thanks, I'm already fixing the bugs you mention. For the board views from Nextcloud, maybe we could add it as an improvement later, for the moment they are shown as read-only.

Great - just make sure that normal tasks appear in the basic task view, and the ones from deck within the boards. I'm completely with you, to get the normal task stuff working properly first. :slightly_smiling_face: :+1:

**Comment by umgpy** [comment]
**Enhancement**: It would be great to add and edit time for scheduled tasks. Currently, Planify shows the scheduled time for task with time added from another source but it cannot add or change the time.

**Comment by alainm23** [comment]
@umgpy I understand what you are saying, I think it is necessary to redesign the date and time selection component, if it allows editing, but it is very confusing to use.

**Comment by BeatLink** [comment]
> @BeatLink Hello old friend, what is your life? haha, thanks for writing, I really do not understand very well the error you comment, could you explain it better, I'm a noob in CalDAV, but I learn fast.

Hey man, I've been good. Been ping ponging between todo apps but this integration has definitely piqued my interest hahaha. 

As others have explained, CalDAV calendars can additionally support tasks, and you can have task only collections and calendar only collections. So Planify would need to load only task only collections and calendar collections with tasks.

**Comment by alainm23** [comment]
Hello guys, I have another version to test the CalDAV integration.

https://github.com/alainm23/planify/actions/runs/7730017027/artifacts/1209594264

- Support for task and event type calendars.
- CalDAV now uses libsecret to store user's account password (You will need to delete your account and re-sync).
- Planify now updates your account every 15 min.
- Fixed bug that removed tags from a task.
- Fixed bug when deleting main task with sub tasks.
- Fixed bug when dragging a sub task into a parent task.

**Comment by alainm23** [comment]
I'm not sure about adding the option to edit a synchronised account. On the other hand it would only remain to support recurring tasks.

**Comment by bepolymathe** [comment]
> Hello guys, I have another version to test the CalDAV integration.
> 
> https://github.com/alainm23/planify/actions/runs/7730017027/artifacts/1209594264
> 
>     * Support for task and event type calendars.
> 
>     * CalDAV now uses libsecret to store user's account password (You will need to delete your account and re-sync).
> 
>     * Planify now updates your account every 15 min.
> 
>     * Fixed bug that removed tags from a task.
> 
>     * Fixed bug when deleting main task with sub tasks.
> 
>     * Fixed bug when dragging a sub task into a parent task.

I have a crash... 

![image](https://github.com/alainm23/planify/assets/29939805/2927776a-1510-485b-8591-0308018facec)

**Comment by umgpy** [comment]
After updating here are some issues I had
Bug: 
* Some Sub tasks still appear as Main tasks. (could be because instead of clean install I updated)
* Scheduled shows the number of scheduled tasks but when open no tasks are displayed from nextcloud, only local tasks are shown. While today correctly displays from nextcloud.
* Completed tasks/subtask when unmarked on nextcloud do not reappear on Planify.

  
[Screencast from 2024-02-01 13-58-29.webm](https://github.com/alainm23/planify/assets/44013803/7658ac4f-e133-46be-a28e-dbc74eaddbf8)


Thanks again for the work!

**Comment by oktayacikalin** [comment]
FEATURE: Planify should always show completed sub-tasks.

I often have tasks having a couple of sub-tasks, which are relevant as a reference while the main gig is running.

Nextcloud Tasks does this too, which is really convenient.

What do you think? Create an issue?

**Comment by alainm23** [comment]
@oktayacikalin Planify already shows the completed subtasks, just enable the option to view completed tasks in the view menu of each project.

![image](https://github.com/alainm23/planify/assets/33765137/e3d26a73-4925-4c83-b275-c74078d8854f)
![image](https://github.com/alainm23/planify/assets/33765137/6fa66769-4592-41b0-b8b9-265f3e75b3d0)

**Comment by oktayacikalin** [comment]
> @oktayacikalin Planify already shows the completed subtasks, just enable the option to view completed tasks in the view menu of each project.

I know that one, but I have about 100 completed tasks per list, which I don't want to see until I do my monthly review and finally remove them. In other lists, I keep them for a year or so just for reference. Always showing those is slowing down the app significantly.

NC Tasks does it differently. By default it hides completed tasks, but shows completed sub-tasks. This keeps the web app snappy, while not hiding important steps of a task (sequence).

**Comment by alainm23** [comment]
I understand, it could be considered as new functionality, could I create the issue to have it tracked? thanks.

**Comment by oktayacikalin** [comment]
BUG: When I create a **task** using the "Create more" feature, it is being created within the Inbox.
BUG: When I create a **sub-task** using the "Create more" feature, it is being created within the Inbox.

**Comment by oktayacikalin** [comment]
> I understand, it could be considered as new functionality, could I create the issue to have it tracked? thanks.

#1126 :slightly_smiling_face:

**Comment by oktayacikalin** [comment]
Here's a task with sub-tasks, which are not shown as a tree in Planify:
[backup-tasks.zip](https://github.com/alainm23/planify/files/14131526/backup-tasks.zip)

I've exported those files by opening each task in Nextcloud and hitting the export button.

**Comment by oktayacikalin** [comment]
Here's another disjointed one. Looks like the relation is not interpreted correctly?

[planify-bug-task-not-associated.zip](https://github.com/alainm23/planify/files/14138802/planify-bug-task-not-associated.zip)

**Comment by alainm23** [comment]
I'm checking, and this is because one of its child tasks is recurring from the parent (and Planify doesn't read it that way). What application are you using to create such recurring tasks? I'm currently using Tasks.org and it doesn't duplicate the task, it just updates the due date on completion of the recurrence.

**Comment by alainm23** [comment]
> BUG: When I create a **task** using the "Create more" feature, it is being created within the Inbox. BUG: When I create a **sub-task** using the "Create more" feature, it is being created within the Inbox.

I have not been able to see the bug, are you still seeing it?

**Comment by oktayacikalin** [comment]
> I'm checking, and this is because one of its child tasks is recurring from the parent (and Planify doesn't read it that way). What application are you using to create such recurring tasks? I'm currently using Tasks.org and it doesn't duplicate the task, it just updates the due date on completion of the recurrence.

I'm using OpenTasks and aCalendar+ in combination. OpenTasks is great for shopping lists and aCalendar+ gives me a proper tree, apart from combining my calendars and tasks into one view. Look into the ical files. It tells who created the items.
OpenTasks and aCalendar also do not duplicate the tasks on completion of the recurrence. I think, they complete and reopen them. I found logs in Nextcloud which tell, that I reopened the reoccurring task.

**Comment by oktayacikalin** [comment]
> > BUG: When I create a **task** using the "Create more" feature, it is being created within the Inbox. BUG: When I create a **sub-task** using the "Create more" feature, it is being created within the Inbox.
> 
> I have not been able to see the bug, are you still seeing it?

Yes, I do:

[Bildschirmaufzeichnung vom 2024-02-03, 01-14-19.webm](https://github.com/alainm23/planify/assets/687189/bb3fc102-42f8-4115-b710-80fedbb537ff)

**Comment by azzamsa** [comment]
I get this when trying to login

The same credentials and URL work fine with `task.org android app`.

---


![image](https://github.com/alainm23/planify/assets/17734314/da15ae74-a668-4a8f-93b3-9281afe4157c)

- [Nextcloud Hub 3](https://nextcloud.com/) (25.0.7)

- Can't check the planify version, because the app keeps crashing when opening `about`

```
🐔 ❯ flatpak run io.github.alainm23.planify.Devel
Date: 2024-02-05T05:37:39+0700

(io.github.alainm23.planify.Devel:2): Gtk-CRITICAL **: 05:37:39.536: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify.Devel:2): Gtk-CRITICAL **: 05:37:39.786: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify.Devel:2): Adwaita-ERROR **: 05:37:41.806: Could not parse metadata file: The resource at “/io/github/alainm23/planify/io.github.alainm23.planify.Devel.appdata.xml.in.in” does not exist
```

```
Planify                io.github.alainm23.planify        4.4             stable      flathub      user
Planify                io.github.alainm23.planify.Devel  4.4             master      devel-origin system
```

```
## Software Information:
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.3
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.13-200.fc39.x86_64
```

**Comment by alainm23** [comment]
@azzamsa  We only tested on Nextcloud Hub 7 onwards, maybe you have a test user you can share with me? we are a bit limited on resources.

**Comment by azzamsa** [comment]
Whoa. I am very surprised that my Nextcloud is that old. It is a bundled version with MailInABox. So that's expected.

I will try the latest Nextcloud release and report back here.

Thank you sooo much for planify! 🧁

**Comment by Nico7as** [comment]
> I would like to know your opinion, the CalDAV account does not have permission to edit the Deck type task lists, only viewing, should Planify?


YES YES YES !!!

It would be a great to be able to use Planify's Board views to interact with Nextcloud Deck ! 
For now, there's only the Android official app to interact with Deck, outside of its webapp.

**Comment by Tettsch** [comment]
Thanks for your great work!

I have installed the latest version you provided here, but when I try to add my Nextcloud server to planify, the app just crashes with the following error:

```
ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
Bail out! ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
```

I can restart the app, and in the preferences it seems like I am logged in to Nextcloud, but sync does not work at all. Unfortunately, there are also no error messages i could provde.

**Comment by alainm23** [comment]
Hi guys, sorry, I've had a lot of workload that didn't allow me to move forward with the last details of this integration, I'm sharing with you a new version of CalDAV support, it brings solutions to the mentioned bugs, recurring tasks and some more things. I will be preparing a new release and doing some more tests. Regards.

https://github.com/alainm23/planify/actions/runs/7941371455/artifacts/1253387840

**Comment by yusyel** [comment]
Caldav support is going to be exclusive for nextcloud?

**Comment by Tettsch** [comment]
> Hi guys, sorry, I've had a lot of workload that didn't allow me to move forward with the last details of this integration, I'm sharing with you a new version of CalDAV support, it brings solutions to the mentioned bugs, recurring tasks and some more things. I will be preparing a new release and doing some more tests. Regards.
> 
> https://github.com/alainm23/planify/actions/runs/7941371455/artifacts/1253387840

Thank you for the new version! Unfortunately, I still have the bug when I  try to connect to my Nextcloud and nothing is synced after I restart Planify.

```
ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
Bail out! ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
```

After restarting Planify, I get the following messages. Maybe that helps :) :

```
F: Not sharing "/usr/share/icons" with sandbox: Path "/usr" is reserved by Flatpak
Date: 2024-02-17T17:05:09+0100
db path: /home/tettscg/.var/app/io.github.alainm23.planify.Devel/data/io.github.alainm23.planify/database.db

(io.github.alainm23.planify.Devel:2): Gtk-CRITICAL **: 17:05:10.227: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify.Devel:2): Gtk-CRITICAL **: 17:05:10.502: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify.Devel:2): Json-CRITICAL **: 17:05:10.672: json_object_get_string_member: assertion 'node != NULL' failed

(io.github.alainm23.planify.Devel:2): GLib-CRITICAL **: 17:05:10.672: g_variant_new_string: assertion 'string != NULL' failed

(io.github.alainm23.planify.Devel:2): GLib-CRITICAL **: 17:05:10.672: g_variant_ref_sink: assertion 'value != NULL' failed

(io.github.alainm23.planify.Devel:2): GLib-GIO-CRITICAL **: 17:05:10.672: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.github.alainm23.planify.Devel:2): GLib-CRITICAL **: 17:05:10.672: g_variant_get_type_string: assertion 'value != NULL' failed

(io.github.alainm23.planify.Devel:2): GLib-GIO-CRITICAL **: 17:05:10.672: g_settings_set_value: key 'todoist-sync-token' in 'io.github.alainm23.planify' expects type 's', but a GVariant of type '(null)' was given

(io.github.alainm23.planify.Devel:2): GLib-CRITICAL **: 17:05:10.672: g_variant_unref: assertion 'value != NULL' failed
```

**Comment by alainm23** [comment]
@Tettsch Sorry, I couldn't reproduce the error, what version of Ntexcloud are you using? And if it would be too much to ask, maybe you could share your account with me just to debug the bug, my personal email is alainmh23@gmail.com.

**Comment by umgpy** [comment]
*App crashes  on clicking 'About Plannify'


```bash
$ flatpak run io.github.alainm23.planify.Devel
Date: 2024-02-18T13:00:37+0100

(io.github.alainm23.planify.Devel:2): Gtk-CRITICAL **: 13:00:38.787: gtk_box_append: assertion 'GTK_IS_WIDGET (child)' failed

(io.github.alainm23.planify.Devel:2): Gtk-CRITICAL **: 13:00:39.031: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify.Devel:2): Gtk-CRITICAL **: 13:00:39.031: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify.Devel:2): Gtk-CRITICAL **: 13:00:39.031: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify.Devel:2): Gtk-CRITICAL **: 13:00:39.032: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify.Devel:2): Gtk-CRITICAL **: 13:00:39.033: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify.Devel:2): Gtk-CRITICAL **: 13:00:39.034: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify.Devel:2): Gtk-CRITICAL **: 13:00:39.036: gtk_stack_set_visible_child_name: assertion 'GTK_IS_STACK (stack)' failed

(io.github.alainm23.planify.Devel:2): Json-CRITICAL **: 13:00:39.490: json_object_get_string_member: assertion 'node != NULL' failed

(io.github.alainm23.planify.Devel:2): GLib-CRITICAL **: 13:00:39.490: g_variant_new_string: assertion 'string != NULL' failed

(io.github.alainm23.planify.Devel:2): GLib-CRITICAL **: 13:00:39.490: g_variant_ref_sink: assertion 'value != NULL' failed

(io.github.alainm23.planify.Devel:2): GLib-GIO-CRITICAL **: 13:00:39.490: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.github.alainm23.planify.Devel:2): GLib-CRITICAL **: 13:00:39.490: g_variant_get_type_string: assertion 'value != NULL' failed

(io.github.alainm23.planify.Devel:2): GLib-GIO-CRITICAL **: 13:00:39.490: g_settings_set_value: key 'todoist-sync-token' in 'io.github.alainm23.planify' expects type 's', but a GVariant of type '(null)' was given

(io.github.alainm23.planify.Devel:2): GLib-CRITICAL **: 13:00:39.490: g_variant_unref: assertion 'value != NULL' failed

(io.github.alainm23.planify.Devel:2): Adwaita-ERROR **: 13:00:41.737: Could not parse metadata file: The resource at “/io/github/alainm23/planify/io.github.alainm23.planify.Devel.appdata.xml.in.in” does not exist
```

*Recurrent Task changes to today from the day and time selected after choosing when to repeat.

Seems to only trigger when choosing weekly I believe.

In action
[Screencast from 2024-02-19 13-08-52.webm](https://github.com/alainm23/planify/assets/44013803/ada58bfe-a850-47fd-9d6d-e104b4a10307)

Log
[log_2.txt](https://github.com/alainm23/planify/files/14331094/log_2.txt)

*Inbox doesn't show any tasks from Nextcloud
